services:
  postgres:
    image: postgis/postgis:16-master
    container_name: PostgresDBPets
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data_db:/var/lib/postgresql

  redis:
    image: redis:7-alpine
    container_name: PetRadarRedis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  postgres_data_db:
  redis_data:
